export const DATAGRID_LOAD_DATA_SUCCESS = 'DATAGRID_LOAD_DATA_SUCCESS';
export type DATAGRID_LOAD_DATA_SUCCESS = typeof DATAGRID_LOAD_DATA_SUCCESS;

export const DATAGRID_LOAD_MORE_SUCCESS = 'DATAGRID_LOAD_MORE_SUCCESS';
export type DATAGRID_LOAD_MORE_SUCCESS = typeof DATAGRID_LOAD_MORE_SUCCESS;

export const DATAGRID_CHANGE_SELECTION = 'DATAGRID_CHANGE_SELECTION';
export type DATAGRID_CHANGE_SELECTION = typeof DATAGRID_CHANGE_SELECTION;

export const DATAGRID_CLEAR_DATA = 'DATAGRID_CLEAR_DATA';
export type DATAGRID_CLEAR_DATA = typeof DATAGRID_CLEAR_DATA;


// WEBPACK FOOTER //
// ./src/modules/shared/constants/data-grid.constants.ts