export const DETAIL_PAGE_LOAD_SUCCESS = 'DETAIL_PAGE_LOAD_SUCCESS'
export type DETAIL_PAGE_LOAD_SUCCESS = typeof DETAIL_PAGE_LOAD_SUCCESS;

export const DETAIL_PAGE_SAVE_SUCCESS = 'DETAIL_PAGE_SAVE_SUCCESS'
export type DETAIL_PAGE_SAVE_SUCCESS = typeof DETAIL_PAGE_SAVE_SUCCESS;

export const DETAIL_PAGE_DELETE_SUCCESS = 'DETAIL_PAGE_DELETE_SUCCESS'
export type DETAIL_PAGE_DELETE_SUCCESS = typeof DETAIL_PAGE_DELETE_SUCCESS;

export const DETAIL_PAGE_CLEAR_STORE = 'DETAIL_PAGE_CLEAR_STORE'
export type DETAIL_PAGE_CLEAR_STORE = typeof DETAIL_PAGE_CLEAR_STORE;


// WEBPACK FOOTER //
// ./src/modules/shared/constants/detail-page.constants.ts