export const softwareRoles: string[] = [
    'PLATFORM_ADMIN', 'CIC_SIT_ENGINEER', 'CIC_CLIENT_SUPPORT_ENGINEER',
    'CIC_FIELD_TECHNICIAN', 'CIC_SALES_MANAGER', 'CIC_PRODUCTION_MANAGER',
    'CIC_DEVOPS_MANAGER', 'CIC_FINANCE_MANAGER', 'CIC_CHANNEL_SALES_MANAGER',
    'CUSTOMER_ADMIN', 'CABINET_ADMIN', 'SECURITY_USER_ADMIN', 'BUSINESS_USER_ADMIN', 'SYSTEM_MONITOR'
];


// WEBPACK FOOTER //
// ./src/modules/users/constants/user-roles.constants.ts