export const LOAD_CABINET_GROUP = 'LOAD_CABINET_GROUP'
export type LOAD_CABINET_GROUP = typeof LOAD_CABINET_GROUP

export const LOAD_SITE = 'LOAD_SITE'
export type LOAD_SITE = typeof LOAD_SITE

export const CABINET_GROUPS_LOADED = 'CABINET_GROUPS_LOADED'
export type CABINET_GROUPS_LOADED = typeof CABINET_GROUPS_LOADED

export const SITES_LOADED = 'SITES_LOADED'
export type SITES_LOADED = typeof SITES_LOADED

export const CABINETS_LOADED = 'CABINETS_LOADED'
export type CABINETS_LOADED = typeof CABINETS_LOADED

export const CUSTOMERS_LOADED = 'CUSTOMERS_LOADED'
export type CUSTOMERS_LOADED = typeof CUSTOMERS_LOADED

export const CABINET_SUMMARY_CHANGED = 'CABINET_SUMMARY_CHANGED'
// export type CABINET_GROUP_CHANGED = typeof CABINET_SUMMARY_CHANGED
export type SITE_CHANGED = typeof CABINET_SUMMARY_CHANGED

export const CABINETS_SUMMARY_LIST_LOADED = 'CABINETS_SUMMARY_LIST_LOADED'
export type CABINETS_SUMMARY_LIST_LOADED = typeof CABINETS_SUMMARY_LIST_LOADED

export const CABINET_ALARMS_LOADED = 'CABINET_ALARMS_LOADED'
export type CABINET_ALARMS_LOADED = typeof CABINET_ALARMS_LOADED

export const ITEM_EVENT_STATS_LOADED = 'ITEM_EVENT_STATS_LOADED'
export type ITEM_EVENT_STATS_LOADED = typeof ITEM_EVENT_STATS_LOADED

export const ALARM_STATS_LOADED = 'ALARM_STATS_LOADED'
export type ALARM_STATS_LOADED = typeof ALARM_STATS_LOADED

export const DASHBOARD_FILTER_CHANGED = 'DASHBOARD_FILTER_CHANGED'
export type DASHBOARD_FILTER_CHANGED = typeof DASHBOARD_FILTER_CHANGED

export const USERS_LOADED = 'USERS_LOADED'
export type USERS_LOADED = typeof USERS_LOADED

export const ACCESS_GROUPS_LOADED = 'ACCESS_GROUPS_LOADED'
export type ACCESS_GROUPS_LOADED = typeof ACCESS_GROUPS_LOADED

export const DASHBOARD_ITEM_STATUS_UPDATED = 'DASHBOARD_ITEM_STATUS_UPDATED'
export type DASHBOARD_ITEM_STATUS_UPDATED = typeof DASHBOARD_ITEM_STATUS_UPDATED

export const DASHBOARD_ALARM_STATUS_UPDATED = 'DASHBOARD_ALARM_STATUS_UPDATED'
export type DASHBOARD_ALARM_STATUS_UPDATED = typeof DASHBOARD_ALARM_STATUS_UPDATED


// WEBPACK FOOTER //
// ./src/modules/dashboard/constants/dashboard.constants.ts