export const DEVICE_UPDATE_STATUS_LOADED = 'DEVICE_UPDATE_STATUS_LOADED'
export type DEVICE_UPDATE_STATUS_LOADED = typeof DEVICE_UPDATE_STATUS_LOADED

export const DEVICE_UPDATE_STATUS_UPDATED = 'DEVICE_UPDATE_STATUS_UPDATED'
export type DEVICE_UPDATE_STATUS_UPDATED = typeof DEVICE_UPDATE_STATUS_UPDATED


// WEBPACK FOOTER //
// ./src/modules/deviceUpdates/constants/device-update.constants.ts