export const LOAD_CABINET = 'LOAD_CABINET'
export type LOAD_CABINET = typeof LOAD_CABINET

export const CHANGE_TOUCH_SCREEN = 'CHANGE_TOUCH_SCREEN'
export type CHANGE_TOUCH_SCREEN = typeof CHANGE_TOUCH_SCREEN

export const CHANGE_TOUCH_SCREEN_WITH_OUT_ITEM_STATES = 'CHANGE_TOUCH_SCREEN_WITH_OUT_ITEM_STATES'
export type CHANGE_TOUCH_SCREEN_WITH_OUT_ITEM_STATES = typeof CHANGE_TOUCH_SCREEN_WITH_OUT_ITEM_STATES

export const SET_GLOBAL_TIMER_STATE = 'SET_GLOBAL_TIMER_STATE'
export type SET_GLOBAL_TIMER_STATE = typeof SET_GLOBAL_TIMER_STATE

export const RESET_CABINET_TIMER = 'RESET_CABINET_TIMER'
export type RESET_CABINET_TIMER = typeof RESET_CABINET_TIMER

export const CABINET_TIMER_ELAPSED = 'CABINET_TIMER_ELAPSED'
export type CABINET_TIMER_ELAPSED = typeof CABINET_TIMER_ELAPSED

export const CABINET_TIMER_STARTED = 'CABINET_TIMER_STARTED'
export type CABINET_TIMER_STARTED = typeof CABINET_TIMER_STARTED

export const SIGN_OUT = 'SIGN_OUT'
export type SIGN_OUT = typeof SIGN_OUT

export const UNLOAD_CABINET = 'UNLOAD_CABINET'
export type UNLOAD_CABINET = typeof UNLOAD_CABINET

export const PROVISION_SUCCESS =  'PROVISION_SUCCESS'
export type PROVISION_SUCCESS = typeof PROVISION_SUCCESS

export const CABINET_LOGIN_SUCCESS =  'CABINET_LOGIN_SUCCESS'
export type CABINET_LOGIN_SUCCESS = typeof CABINET_LOGIN_SUCCESS

export const CABINET_LOGIN_ERROR =  'CABINET_LOGIN_ERROR'
export type CABINET_LOGIN_ERROR = typeof CABINET_LOGIN_ERROR

export const TOGGLE_DOOR = 'TOGGLE_DOOR'
export type TOGGLE_DOOR = typeof TOGGLE_DOOR

export const TOGGLE_DOOR_TIMER = 'TOGGLE_DOOR_TIMER'
export type TOGGLE_DOOR_TIMER = typeof TOGGLE_DOOR_TIMER

export const TOGGLE_POWER = 'TOGGLE_POWER'
export type TOGGLE_POWER = typeof TOGGLE_POWER

export const TOGGLE_NETWORK = 'TOGGLE_NETWORK'
export type TOGGLE_NETWORK = typeof TOGGLE_NETWORK

export const TOGGLE_ITEM = 'TOGGLE_ITEM'
export type TOGGLE_ITEM = typeof TOGGLE_ITEM

export const TOGGLE_ITEM_SUCCESS = 'TOGGLE_ITEM_SUCCESS'
export type TOGGLE_ITEM_SUCCESS = typeof TOGGLE_ITEM_SUCCESS

export const BLINK_ITEM = 'BLINK_ITEM'
export type BLINK_ITEM = typeof BLINK_ITEM

export const STOP_BLINK_ITEM = 'STOP_BLINK_ITEM'
export type STOP_BLINK_ITEM = typeof STOP_BLINK_ITEM

export const TOGGLE_RELAY = 'TOGGLE_RELAY'
export type TOGGLE_RELAY = typeof TOGGLE_RELAY

export const TRIGGER_TOUCH_SCREEN_INTERACTION = 'TRIGGER_TOUCH_SCREEN_INTERACTION'
export type TRIGGER_TOUCH_SCREEN_INTERACTION = typeof TRIGGER_TOUCH_SCREEN_INTERACTION

export const LOAD_CABINET_TWIN = 'LOAD_CABINET_TWIN'
export type LOAD_CABINET_TWIN = typeof LOAD_CABINET_TWIN

export const LOAD_CABINET_EVENTS = 'LOAD_CABINET_EVENTS'
export type LOAD_CABINET_EVENTS = typeof LOAD_CABINET_EVENTS

export const LOAD_CABINET_ITEM_EVENTS = 'LOAD_CABINET_ITEM_EVENTS'
export type LOAD_CABINET_ITEM_EVENTS = typeof LOAD_CABINET_ITEM_EVENTS

export const LOAD_TOUCH_SCREEN_CABINET_EVENTS = 'LOAD_TOUCH_SCREEN_CABINET_EVENTS'
export type LOAD_TOUCH_SCREEN_CABINET_EVENTS = typeof LOAD_TOUCH_SCREEN_CABINET_EVENTS

export const CLEAR_CABINET_EVENT_HISTORY = 'CLEAR_CABINET_EVENT_HISTORY'
export type CLEAR_CABINET_EVENT_HISTORY = typeof CLEAR_CABINET_EVENT_HISTORY

export const CLEAR_CABINET_ITEM_EVENT_HISTORY = 'CLEAR_CABINET_ITEM_EVENT_HISTORY'
export type CLEAR_CABINET_ITEM_EVENT_HISTORY = typeof CLEAR_CABINET_ITEM_EVENT_HISTORY

export const CLEAR_TOUCH_SCREEN_CABINET_EVENT_HISTORY = 'CLEAR_TOUCH_SCREEN_CABINET_EVENT_HISTORY'
export type CLEAR_TOUCH_SCREEN_CABINET_EVENT_HISTORY = typeof CLEAR_TOUCH_SCREEN_CABINET_EVENT_HISTORY

export const QUEUE_EVENT = 'QUEUE_EVENT'
export type QUEUE_EVENT = typeof QUEUE_EVENT

export const DEQUEUE_HIGH_PRIORITY_EVENTS = 'DEQUEUE_HIGH_PRIORITY_EVENTS'
export type DEQUEUE_HIGH_PRIORITY_EVENTS = typeof DEQUEUE_HIGH_PRIORITY_EVENTS

export const DEQUEUE_LOW_PRIORITY_EVENTS = 'DEQUEUE_LOW_PRIORITY_EVENTS'
export type DEQUEUE_LOW_PRIORITY_EVENTS = typeof DEQUEUE_LOW_PRIORITY_EVENTS

export const START_LOW_PRIORITY_EVENT_PUBLISHING = 'START_LOW_PRIORITY_EVENT_PUBLISHING'
export type START_LOW_PRIORITY_EVENT_PUBLISHING = typeof START_LOW_PRIORITY_EVENT_PUBLISHING

export const START_HIGH_PRIORITY_EVENT_PUBLISHING = 'START_HIGH_PRIORITY_EVENT_PUBLISHING'
export type START_HIGH_PRIORITY_EVENT_PUBLISHING = typeof START_HIGH_PRIORITY_EVENT_PUBLISHING

export const STOP_HIGH_PRIORITY_EVENT_PUBLISHING = 'STOP_HIGH_PRIORITY_EVENT_PUBLISHING'
export type STOP_HIGH_PRIORITY_EVENT_PUBLISHING = typeof STOP_HIGH_PRIORITY_EVENT_PUBLISHING

export const STOP_LOW_PRIORITY_EVENT_PUBLISHING = 'STOP_LOW_PRIORITY_EVENT_PUBLISHING'
export type STOP_LOW_PRIORITY_EVENT_PUBLISHING = typeof STOP_LOW_PRIORITY_EVENT_PUBLISHING

export const TRIGGER_MULTI_CUSTODY_LOGIN = 'TRIGGER_MULTI_CUSTODY_LOGIN'
export type TRIGGER_MULTI_CUSTODY_LOGIN = typeof TRIGGER_MULTI_CUSTODY_LOGIN

export const MULTI_CUSTODY_LOGIN = 'MULTI_CUSTODY_LOGIN'
export type MULTI_CUSTODY_LOGIN = typeof MULTI_CUSTODY_LOGIN

export const MULTI_CUSTODY_WITNESS_LOGIN_SUCCESS = 'MULTI_CUSTODY_WITNESS_LOGIN_SUCCESS'
export type MULTI_CUSTODY_WITNESS_LOGIN_SUCCESS = typeof MULTI_CUSTODY_WITNESS_LOGIN_SUCCESS

export const MULTI_CUSTODY_WITNESS_LOGIN_FAIL = 'MULTI_CUSTODY_WITNESS_LOGIN_FAIL'
export type MULTI_CUSTODY_WITNESS_LOGIN_FAIL = typeof MULTI_CUSTODY_WITNESS_LOGIN_FAIL

export const MULTI_CUSTODY_AUTHENTICATION_COMPLETE = 'MULTI_CUSTODY_AUTHENTICATION_COMPLETE'
export type MULTI_CUSTODY_AUTHENTICATION_COMPLETE = typeof MULTI_CUSTODY_AUTHENTICATION_COMPLETE

export const MULTI_CUSTODY_AUTHENTICATION_FAIL = 'MULTI_CUSTODY_AUTHENTICATION_FAIL'
export type MULTI_CUSTODY_AUTHENTICATION_FAIL = typeof MULTI_CUSTODY_AUTHENTICATION_FAIL

export const SWITCH_TO_MAIN_MENU_ON_MULTI_CUSTODY_AUTH_FAIL = 'SWITCH_TO_MAIN_MENU_ON_MULTI_CUSTODY_AUTH_FAIL'
export type SWITCH_TO_MAIN_MENU_ON_MULTI_CUSTODY_AUTH_FAIL = typeof SWITCH_TO_MAIN_MENU_ON_MULTI_CUSTODY_AUTH_FAIL

export const WITNESS_USER_TIMEOUT = 'WITNESS_USER_TIMEOUT'
export type WITNESS_USER_TIMEOUT = typeof WITNESS_USER_TIMEOUT

export const SHOW_TOUCHSCREEN_POPUP = 'SHOW_TOUCHSCREEN_POPUP'
export type SHOW_TOUCHSCREEN_POPUP = typeof SHOW_TOUCHSCREEN_POPUP

export const HIDE_TOUCHSCREEN_POPUP = 'HIDE_TOUCHSCREEN_POPUP'
export type HIDE_TOUCHSCREEN_POPUP = typeof HIDE_TOUCHSCREEN_POPUP



// WEBPACK FOOTER //
// ./src/modules/cabinet/constants/cabinet-control-center.constants.ts