export const ALL_ACTIVE_ALARM_STATS_LOADED = 'ALL_ACTIVE_ALARM_STATS_LOADED'
export type ALL_ACTIVE_ALARM_STATS_LOADED = typeof ALL_ACTIVE_ALARM_STATS_LOADED

export const ACTIVE_ALARM_STATS_UPDATED = 'ACTIVE_ALARM_STATS_UPDATED'
export type ACTIVE_ALARM_STATS_UPDATED = typeof ACTIVE_ALARM_STATS_UPDATED


// WEBPACK FOOTER //
// ./src/modules/eventAlarms/constants/alarm.constants.ts